/* Base de recettes — SCRAPÉE depuis Marmiton / Saveurs / Journal des Femmes.
   Généré par build_data.py — ne pas éditer à la main. */
window.RECIPES = [
  {"nom": "Émincés de poulet sauce moutarde", "cat": "Volaille", "proteine": "volaille", "source": "Marmiton", "url": "https://www.marmiton.org/recettes/recette_eminces-de-poulet-sauce-moutarde_73046.aspx", "prep_min": 10, "cuisson_min": 8, "total_min": 18, "cuissons": ["poêle"], "parts_origine": 4, "saison": "Toute l'année", "tags": [], "ingredients": [{"nom": "oignon", "qte": 1, "unite": "unité", "rayon": "Fruits & légumes"}, {"nom": "moutarde", "qte": 3, "unite": "cuillères à soupe", "rayon": "Épicerie"}, {"nom": "crème fraîche épaisse", "qte": 1, "unite": "pot", "rayon": "Crèmerie"}, {"nom": "blancs de poulet", "qte": 4, "unite": "unités", "rayon": "Boucherie"}], "etapes": ["Découper l'oignon en petit morceaux et le poulet en lamelles.", "Verser un peu d'huile d'olive dans une poêle et les faire dorer.", "Lorsque le tout est cuit, baisser le feu et ajouter la crème fraîche et la moutarde.", "Saler et poivrer et ajouter un peu d'ail semoule.", "Cette recette se déguste avec du riz ou du blé."]},
  {"nom": "Poulet au curry lait de coco et noix de cajou", "cat": "Volaille", "proteine": "volaille", "source": "Marmiton", "url": "https://www.marmiton.org/recettes/recette_poulet-au-curry-lait-de-coco-et-noix-de-cajou_37398.aspx", "prep_min": 10, "cuisson_min": 15, "total_min": 25, "cuissons": ["poêle"], "parts_origine": 3, "saison": "Toute l'année", "tags": [], "ingredients": [{"nom": "maïzena", "qte": 1, "unite": "cuillère à soupe", "rayon": "Épicerie"}, {"nom": "huile", "qte": 3, "unite": "cuillères à soupe", "rayon": "Épicerie"}, {"nom": "curry", "qte": 1, "unite": "cuillère à café", "rayon": "Épicerie"}, {"nom": "filets de poulet", "qte": 3, "unite": "filets", "rayon": "Boucherie"}, {"nom": "lait de coco", "qte": 20, "unite": "cl", "rayon": "Épicerie"}, {"nom": "sauce soja", "qte": 1, "unite": "cuillère à soupe", "rayon": "Épicerie"}, {"nom": "noix de cajou", "qte": 1, "unite": "poignée", "rayon": "Épicerie"}], "etapes": ["Concasser les noix de cajou (culot d'un verre dans une assiette à soupe) pour obtenir de la poudre et des petits morceaux.", "Couper les filets de poulet en morceaux d'environ 1 à 2 cm cube ou en lanières fines. Les passer dans la maïzena.", "Faire chauffer le curry dans l'huile chaude jusqu'à ce que ses parfums s'exhalent.", "Ajouter le poulet et laisser dorer durant 5 minutes.", "Verser la sauce soja puis la crème de coco. Mélanger puis laisser cuire 10 minutes. Ajouter les noix de cajou 5 minutes avant la fin. Saler, poivrer."]},
  {"nom": "Émincés de dinde aux poireaux", "cat": "Volaille", "proteine": "volaille", "source": "Journal des Femmes", "url": "https://cuisine.journaldesfemmes.fr/recette/337850-eminces-de-dinde", "prep_min": 20, "cuisson_min": 15, "total_min": 35, "cuissons": ["poêle"], "parts_origine": 4, "saison": "Automne-hiver", "tags": [], "ingredients": [{"nom": "escalopes de dinde", "qte": 4, "unite": "pièce", "rayon": "Boucherie"}, {"nom": "poireaux", "qte": 200, "unite": "g", "rayon": "Fruits & légumes"}, {"nom": "échalote", "qte": 1, "unite": "pièce", "rayon": "Fruits & légumes"}, {"nom": "yaourt nature 0%", "qte": 1, "unite": "pièce", "rayon": "Crèmerie"}, {"nom": "moutarde", "qte": 2, "unite": "cuillères", "rayon": "Épicerie"}, {"nom": "curry", "qte": 1, "unite": "cuillère", "rayon": "Épicerie"}, {"nom": "sésame", "qte": 1, "unite": "cuillère", "rayon": "Épicerie"}, {"nom": "beurre", "qte": 1, "unite": "noisette", "rayon": "Crèmerie"}], "etapes": ["Émincer les escalopes de dinde en lanières fines. Couper l'échalote.", "Faire revenir avec du beurre la dinde et l'échalote jusqu'à ce que ce soit doré.", "Ajouter les poireaux, faire cuire à couvert 15 minutes avec un peu d'eau.", "Mélanger le yaourt, la moutarde, le curry et le sésame.", "Ajouter à la préparation dinde-poireaux et cuire 2-3 minutes à feu très doux.", "Assaisonner de sel et de poivre selon votre convenance."]},
  {"nom": "Escalopes de poulet panées", "cat": "Volaille", "proteine": "volaille", "source": "Marmiton", "url": "https://www.marmiton.org/recettes/recette_escalopes-de-poulet-panees_21501.aspx", "prep_min": 10, "cuisson_min": 10, "total_min": 20, "cuissons": ["poêle"], "parts_origine": 2, "saison": "Toute l'année", "tags": [], "ingredients": [{"nom": "farine", "qte": 2, "unite": "cuillères à soupe", "rayon": "Épicerie"}, {"nom": "escalopes de poulet", "qte": 2, "unite": "unités", "rayon": "Boucherie"}, {"nom": "biscottes", "qte": 5, "unite": "unités", "rayon": "Boulangerie"}, {"nom": "oeuf", "qte": 1, "unite": "unités", "rayon": "Crèmerie"}, {"nom": "paprika", "qte": 1, "unite": "petite cuillère à soupe", "rayon": "Épicerie"}], "etapes": ["Tailler le poulet en languettes d'environ 10 cm sur 5 cm.", "Battre l'oeuf avec le paprika.", "Ecraser les biscottes et les mélanger à la farine et saler.", "Faire chauffer de l'huile dans une grande poêle, tremper chaque languette de poulet dans l'oeuf puis dans la biscotte et faire frire 5 mn de chaque côté.", "Bien égoutter sur du papier absorbant et re-saler si nécessaire.", "Le poulet reste tendre et moelleux."]},
  {"nom": "Émincé de poulet au citron", "cat": "Volaille", "proteine": "volaille", "source": "Marmiton", "url": "https://www.marmiton.org/recettes/recette_emince-de-poulet-au-citron-facile_16645.aspx", "prep_min": 15, "cuisson_min": 5, "total_min": 20, "cuissons": ["poêle"], "parts_origine": 2, "saison": "Toute l'année", "tags": [], "ingredients": [{"nom": "blanc de poulet", "qte": 2, "unite": "unités", "rayon": "Boucherie"}, {"nom": "oignon", "qte": 1, "unite": "unités", "rayon": "Fruits & légumes"}, {"nom": "citron", "qte": 1, "unite": "unités", "rayon": "Fruits & légumes"}, {"nom": "sel", "qte": 1, "unite": "pincée", "rayon": "Épicerie"}, {"nom": "poivre", "qte": 1, "unite": "pincée", "rayon": "Épicerie"}, {"nom": "piment en poudre", "qte": 1, "unite": "pincée", "rayon": "Épicerie"}, {"nom": "paprika", "qte": 1, "unite": "pincée", "rayon": "Épicerie"}], "etapes": ["Découper les blancs de poulet en longues et fines lamelles.", "Les saupoudrer généreusement de toutes les épices (sel, poivre, piment, paprika), puis les mettre dans un petit récipient et couvrir de jus de citron. Agiter pour bien mélanger si le récipient a un couvercle.", "Pendant que le poulet repose, hacher l'oignon et le faire revenir dans une poêle avec un peu d'huile.", "Lorsque l'oignon a une belle couleur ambrée, égoutter le poulet (sans l'essuyer) et le faire revenir avec l'oignon dans la poêle. Quelques minutes suffisent si les lamelles sont bien fines.", "Servir accompagné de salade ou de riz blanc."]},
  {"nom": "Suprêmes de pintade à la bière", "cat": "Volaille", "proteine": "volaille", "source": "Marmiton", "url": "https://www.marmiton.org/recettes/recette_supreme-de-pintade-a-la-biere_537436.aspx", "prep_min": 15, "cuisson_min": 20, "total_min": 35, "cuissons": ["poêle", "four"], "parts_origine": 4, "saison": "Automne-hiver", "tags": [], "ingredients": [{"nom": "sel", "qte": 1, "unite": "pincée", "rayon": "Épicerie"}, {"nom": "beurre", "qte": 1, "unite": "bonne noix", "rayon": "Crèmerie"}, {"nom": "huile", "qte": 1, "unite": "cuillère à soupe", "rayon": "Épicerie"}, {"nom": "moutarde à l'ancienne", "qte": 8, "unite": "cuillères à soupe", "rayon": "Épicerie"}, {"nom": "romarin", "qte": 2, "unite": "brins", "rayon": "Fruits & légumes"}, {"nom": "suprêmes de pintade", "qte": 4, "unite": "morceaux", "rayon": "Boucherie"}, {"nom": "bière blonde", "qte": 250, "unite": "ml", "rayon": "Épicerie"}, {"nom": "ail", "qte": 1, "unite": "gousse", "rayon": "Fruits & légumes"}, {"nom": "échalotes", "qte": 2, "unite": "pièces", "rayon": "Fruits & légumes"}, {"nom": "poivre du moulin", "qte": 1, "unite": "pincée", "rayon": "Épicerie"}, {"nom": "cannelle", "qte": 1, "unite": "pincée", "rayon": "Épicerie"}], "etapes": ["Pelez l'ail, ôtez-en le germe et émincez-le finement. Pelez les échalotes et ciselez-les.", "Dans une poêle, faites chauffer l'huile et déposez-y les suprêmes de pintade côté peau pour bien les marquer. Salez. Ajoutez le beurre et faites-le mousser. Retournez après 3 minutes, laissez dorer 2 minutes supplémentaires sur l'autre face.", "Sortez les suprêmes de la poêle et laissez-les reposer environ 10 min. Badigeonnez-les de moutarde à l'ancienne. Dans une cocotte allant au four, faites suer l'échalote et l'ail rapidement. Déposez les suprêmes (peau vers le haut) avec le romarin et une pincée de cannelle. Poivrez. Versez la bière.", "Cuire 15 minutes dans un four préchauffé à 220°C en arrosant régulièrement. Servir bien chaud avec des châtaignes sautées, des légumes de saison ou un risotto."]},
  {"nom": "Poulet rôti simple", "cat": "Rôti", "proteine": "volaille", "source": "Marmiton", "url": "https://www.marmiton.org/recettes/recette_poulet-roti-simple_57676.aspx", "prep_min": 10, "cuisson_min": 90, "total_min": 100, "cuissons": ["four"], "parts_origine": 4, "saison": "Toute l'année", "tags": [], "ingredients": [{"nom": "huile végétale", "qte": 1, "unite": "coup", "rayon": "Épicerie"}, {"nom": "poulet entier", "qte": 1, "unite": "kg", "rayon": "Boucherie"}], "etapes": ["Préchauffer le four à 190°.", "Prendre le poulet et le masser avec de l'huile partout, même sous les ailes.", "Laisser la bride.", "Le poser dans un plat et le mettre au four pendant 1h30 (ou 2h si c'est un bio).", "Ne pas le piquer avec une fourchette ou un couteau, ne pas le retourner, ne plus le toucher une fois enfourné : il cuit dans sa peau.", "Pas besoin de l'arroser."]},
  {"nom": "Échine de porc rôtie à l'ail et au romarin", "cat": "Rôti", "proteine": "porc", "source": "Marmiton", "url": "https://www.marmiton.org/recettes/recette_echine-de-porc-rotie-a-la-sauge-et-au-romarin_231772.aspx", "prep_min": 15, "cuisson_min": 120, "total_min": 135, "cuissons": ["cocotte", "four"], "parts_origine": 8, "saison": "Automne-hiver", "tags": [], "ingredients": [{"nom": "oignons", "qte": 2, "unite": "unités", "rayon": "Fruits & légumes"}, {"nom": "huile ou beurre", "qte": 1, "unite": "filet", "rayon": "Crèmerie"}, {"nom": "carottes", "qte": 2, "unite": "unités", "rayon": "Fruits & légumes"}, {"nom": "branche de romarin", "qte": 1, "unite": "unité", "rayon": "Fruits & légumes"}, {"nom": "échine de porc avec l'os", "qte": 800, "unite": "g", "rayon": "Boucherie"}, {"nom": "branche de sauge", "qte": 1, "unite": "unité", "rayon": "Fruits & légumes"}, {"nom": "gousses d'ail", "qte": 3, "unite": "unités", "rayon": "Fruits & légumes"}, {"nom": "vin blanc sec", "qte": 25, "unite": "cl", "rayon": "Épicerie"}], "etapes": ["Piquez le rôti avec l'ail et le romarin.", "Dans une cocotte en fonte, faites chauffer la matière grasse et saisissez le rôti sur toutes ses faces à feu moyen. Placez-le ensuite de sorte à ce qu'il repose sur l'os.", "Ajoutez les oignons grossièrement hachés et les carottes découpées en fines rondelles. Faites suer les légumes 5 min.", "Ajoutez la branche de sauge.", "Déglacez avec le vin blanc.", "Assaisonnez (sel, poivre). Couvrez la cocotte et enfournez à 140°C (thermostat 4).", "Laissez cuire au moins 1h30 en arrosant de temps à autre la viande avec le jus.", "Pour servir, détachez l'os et découpez des tranches.", "Accompagnez avec les légumes de votre choix : haricots verts ou purée."]},
  {"nom": "Épaule d'agneau confite à l'ail et au romarin", "cat": "Rôti", "proteine": "agneau", "source": "Marmiton", "url": "https://www.marmiton.org/recettes/recette_epaule-d-agneau-confite-a-l-ail-et-au-romarin_23030.aspx", "prep_min": 120, "cuisson_min": 120, "total_min": 240, "cuissons": ["cocotte", "four"], "parts_origine": 4, "saison": "Automne-hiver", "tags": [], "ingredients": [{"nom": "huile d'olive", "qte": 2, "unite": "cuillères à soupe", "rayon": "Épicerie"}, {"nom": "gros sel de mer", "qte": 2, "unite": "cuillères à soupe", "rayon": "Épicerie"}, {"nom": "romarin", "qte": 8, "unite": "brins", "rayon": "Fruits & légumes"}, {"nom": "épaule d'agneau désossée", "qte": 1, "unite": "pièce", "rayon": "Boucherie"}, {"nom": "ail", "qte": 8, "unite": "gousses", "rayon": "Fruits & légumes"}, {"nom": "vin blanc", "qte": 3, "unite": "cuillères à soupe", "rayon": "Épicerie"}], "etapes": ["Frottez la viande avec le gros sel et laissez-la reposer 2h. Rincez-la et épongez-la. Coupez en 12 morceaux.", "Allumez le four Th 4 (150°C). Huilez légèrement une cocotte en fonte. Huilez les morceaux de viande avec le reste d'huile et rangez-les dans la cocotte, côté couenne vers le haut. Glissez l'ail et le romarin entre les morceaux. Versez le vin et couvrez la cocotte. Glissez au four et laissez cuire 2h sans y toucher.", "Lorsque la viande est cuite, jetez l'huile et déglacez les sucs de cuisson avec quelques cuillerées d'eau, sur feu vif en remuant avec une spatule. Nappez la viande de ce jus au moment de servir.", "Accompagnez de pommes de terre, d'une salade ou de légumes verts."]},
  {"nom": "Rôti de veau tout simple et parfumé", "cat": "Rôti", "proteine": "veau", "source": "Marmiton", "url": "https://www.marmiton.org/recettes/recette_roti-de-veau-tout-simple_231724.aspx", "prep_min": 10, "cuisson_min": 90, "total_min": 100, "cuissons": ["four"], "parts_origine": 4, "saison": "Toute l'année", "tags": [], "ingredients": [{"nom": "rôti de veau", "qte": 1, "unite": "pièce", "rayon": "Boucherie"}, {"nom": "huile d'olive", "qte": 1, "unite": "filet", "rayon": "Épicerie"}, {"nom": "sel", "qte": 1, "unite": "pincée", "rayon": "Épicerie"}, {"nom": "poivre", "qte": 1, "unite": "pincée", "rayon": "Épicerie"}, {"nom": "oignon", "qte": 1, "unite": "pièce", "rayon": "Fruits & légumes"}, {"nom": "thym", "qte": 1, "unite": "pincée", "rayon": "Fruits & légumes"}, {"nom": "pommes de terre", "qte": 4, "unite": "pièces", "rayon": "Fruits & légumes"}, {"nom": "vin blanc sec", "qte": 1, "unite": "petit verre", "rayon": "Épicerie"}, {"nom": "eau", "qte": 1, "unite": "petit verre", "rayon": "Épicerie"}, {"nom": "bouillon de volaille", "qte": 1, "unite": "cube", "rayon": "Épicerie"}], "etapes": ["Préchauffer le four à thermostat 7 (230°C).", "Dans un plat allant au four, déposer la pièce de rôti.", "Émincer les oignons et les déposer dans le plat autour de la viande.", "Peler et couper en morceaux larges les pommes de terre, les déposer de façon à couvrir les oignons.", "Émietter le cube de bouillon au-dessus du rôti et des pommes de terre.", "Arroser de filets d'huile d'olive. Ajouter le vin blanc et le verre d'eau. Saler, poivrer.", "Saupoudrer d'un peu de thym.", "Mettre le plat au four. Au bout de 30 min, retourner le rôti, et répéter l'opération 30 minutes plus tard.", "Vérifier les pommes de terre et les mélanger si besoin.", "Commencer à vérifier la cuisson au bout de 15 minutes avec la pointe d'un couteau."]},
  {"nom": "Salade de lentilles au saumon fumé", "cat": "Légumineuses", "proteine": "poisson", "source": "Marmiton", "url": "https://www.marmiton.org/recettes/recette_salade-de-lentilles-au-saumon-fume_10712.aspx", "prep_min": 10, "cuisson_min": 5, "total_min": 15, "cuissons": ["sans cuisson"], "parts_origine": 4, "saison": "Toute l'année", "tags": ["poisson gras"], "ingredients": [{"nom": "lentilles en conserve", "qte": 1, "unite": "kg", "rayon": "Épicerie"}, {"nom": "saumon fumé", "qte": 4, "unite": "tranches", "rayon": "Poissonnerie"}, {"nom": "échalotes grises", "qte": 2, "unite": "unités", "rayon": "Fruits & légumes"}, {"nom": "moutarde", "qte": 1, "unite": "cuillère à soupe", "rayon": "Épicerie"}, {"nom": "huile de tournesol", "qte": 3, "unite": "cuillères à soupe", "rayon": "Épicerie"}, {"nom": "vinaigre de framboise", "qte": 1, "unite": "cuillère à soupe", "rayon": "Épicerie"}, {"nom": "ciboulette", "qte": 1, "unite": "bouquet", "rayon": "Fruits & légumes"}], "etapes": ["Rincer les lentilles et les égoutter. Les faire chauffer quelques minutes (elles doivent être tièdes).", "Préparer une sauce à salade avec la moutarde, l'huile de tournesol et le vinaigre de framboise.", "Éplucher et couper les échalotes grises.", "Mettre la sauce sur les lentilles encore tièdes, avec les échalotes. Dresser sur les assiettes.", "Couper les tranches de saumon en lamelles.", "Disposer les lamelles de saumon sur chaque assiette, avec quelques brins de ciboulette."]},
  {"nom": "Dal épinards et lentilles corail au lait de coco", "cat": "Légumineuses", "proteine": "végé", "source": "Marmiton", "url": "https://www.marmiton.org/recettes/recette_dal-epinards-et-lentilles_527981.aspx", "prep_min": 5, "cuisson_min": 25, "total_min": 30, "cuissons": ["casserole", "poêle"], "parts_origine": 4, "saison": "Toute l'année", "tags": ["végé"], "ingredients": [{"nom": "lentilles corail", "qte": 300, "unite": "g", "rayon": "Épicerie"}, {"nom": "épinards", "qte": 300, "unite": "g", "rayon": "Fruits & légumes"}, {"nom": "lait de coco", "qte": 200, "unite": "ml", "rayon": "Épicerie"}, {"nom": "bouillon de légumes", "qte": 600, "unite": "ml", "rayon": "Épicerie"}, {"nom": "gingembre moulu", "qte": 1, "unite": "cuillère à café", "rayon": "Épicerie"}, {"nom": "cumin", "qte": 1, "unite": "cuillère à café", "rayon": "Épicerie"}, {"nom": "garam masala", "qte": 1, "unite": "cuillère à café", "rayon": "Épicerie"}, {"nom": "graine de moutarde", "qte": 1, "unite": "cuillère à café", "rayon": "Épicerie"}, {"nom": "échalotes", "qte": 4, "unite": "unités", "rayon": "Fruits & légumes"}, {"nom": "ail", "qte": 3, "unite": "gousses", "rayon": "Fruits & légumes"}, {"nom": "coriandre", "qte": 1, "unite": "bouquet", "rayon": "Fruits & légumes"}, {"nom": "piment", "qte": 1, "unite": "pincée", "rayon": "Épicerie"}, {"nom": "huile d'arachide", "qte": 1, "unite": "cuillère à soupe", "rayon": "Épicerie"}], "etapes": ["Rincez les lentilles à l'eau froide. Égouttez-les et mettez-les à la casserole avec le lait de coco, le bouillon, le cumin, la coriandre, le curcuma et le gingembre.", "Portez à ébullition, couvrez et faites cuire 15 à 20 minutes à feu doux. Remuez régulièrement pour éviter que les lentilles attachent.", "Ajoutez les épinards et faites cuire 6 à 8 minutes, jusqu'à ce que les lentilles soient tendres. Ajoutez un peu d'eau ou de bouillon si ça devient trop épais.", "Pendant ce temps, préparez le tarka.", "Dans une petite poêle, faites chauffer l'huile pour y faire revenir les ingrédients jusqu'à ce que les échalotes soient dorées.", "Ajoutez ce mélange au dal. Enfin, ajoutez le garam masala et la coriandre hachée."]},
  {"nom": "Petit salé aux lentilles vertes, carotte et lardons fumés", "cat": "Légumineuses", "proteine": "porc", "source": "Marmiton", "url": "https://www.marmiton.org/recettes/recette_lentilles-vertes-au-petit-sale_533031.aspx", "prep_min": 10, "cuisson_min": 40, "total_min": 50, "cuissons": ["cocotte"], "parts_origine": 4, "saison": "Automne-hiver", "tags": ["charcuterie"], "ingredients": [{"nom": "lardons fumés", "qte": 200, "unite": "g", "rayon": "Boucherie"}, {"nom": "lentilles vertes", "qte": 150, "unite": "g", "rayon": "Épicerie"}, {"nom": "carotte", "qte": 1, "unite": "unité", "rayon": "Fruits & légumes"}, {"nom": "échalote", "qte": 3, "unite": "unités", "rayon": "Fruits & légumes"}, {"nom": "herbes de Provence", "qte": 1, "unite": "cuillère à café", "rayon": "Épicerie"}, {"nom": "huile de tournesol", "qte": 2, "unite": "cuillères à soupe", "rayon": "Épicerie"}], "etapes": ["Faites dorer les lardons dans l'huile de tournesol, pendant 10 minutes à feu vif, avec les échalotes coupées en morceaux et les herbes de Provence.", "Ajoutez les lentilles et la carotte coupée en rondelles et 50 cl d'eau. Mélangez bien.", "Laissez mijoter environ 30 minutes jusqu'à ce que les lentilles soient tendres, en remuant de temps en temps. Ajoutez un peu d'eau si nécessaire.", "C'est prêt. Bon appétit !"]},
  {"nom": "Curry de pois chiches au lait de coco", "cat": "Légumineuses", "proteine": "végé", "source": "Marmiton", "url": "https://www.marmiton.org/recettes/recette_curry-de-pois-chiches-au-lait-de-coco_224063.aspx", "prep_min": 10, "cuisson_min": 10, "total_min": 20, "cuissons": ["casserole"], "parts_origine": 4, "saison": "Toute l'année", "tags": ["végé"], "ingredients": [{"nom": "pois chiches", "qte": 500, "unite": "g", "rayon": "Épicerie"}, {"nom": "lait de coco", "qte": 20, "unite": "cl", "rayon": "Épicerie"}, {"nom": "curry", "qte": 3, "unite": "cuillères à café", "rayon": "Épicerie"}, {"nom": "coriandre moulue", "qte": 3, "unite": "cuillères à café", "rayon": "Épicerie"}, {"nom": "gingembre frais", "qte": 1, "unite": "morceau", "rayon": "Fruits & légumes"}, {"nom": "coriandre fraîche", "qte": 1, "unite": "bouquet", "rayon": "Fruits & légumes"}, {"nom": "sel", "qte": 1, "unite": "pincée", "rayon": "Épicerie"}], "etapes": ["Verser les pois chiches dans une casserole, ajouter le curry, la coriandre puis le gingembre pelé et râpé : chauffer à feu moyen 10 min.", "Ajouter 4 cuillères à soupe de lait de coco. Chauffer 3 min. Saler avant de servir.", "Ajouter de la coriandre fraîche pour la présentation et la touche fraîcheur."]},
  {"nom": "Salade de lentilles, pois chiches et thon", "cat": "Légumineuses", "proteine": "poisson", "source": "Marmiton", "url": "https://www.marmiton.org/recettes/recette_salade-lentilles-pois-chiches-thon_33249.aspx", "prep_min": 40, "cuisson_min": 35, "total_min": 75, "cuissons": ["casserole"], "parts_origine": 4, "saison": "Printemps-été", "tags": ["poisson gras"], "ingredients": [{"nom": "lentilles vertes", "qte": 250, "unite": "g", "rayon": "Épicerie"}, {"nom": "pois chiches", "qte": 1, "unite": "petite boîte", "rayon": "Épicerie"}, {"nom": "thon albacore", "qte": 2, "unite": "boîtes", "rayon": "Épicerie"}, {"nom": "oignons", "qte": 2, "unite": "unités", "rayon": "Fruits & légumes"}, {"nom": "carotte", "qte": 1, "unite": "unité", "rayon": "Fruits & légumes"}, {"nom": "vinaigrette", "qte": 1, "unite": "portion", "rayon": "Épicerie"}], "etapes": ["Faire cuire les lentilles avec la carotte coupée en rondelles et les oignons émincés pendant 25 à 35 mn.", "Pendant ce temps mélanger les boîtes de thon avec les pois chiches dans un saladier.", "Préparer la vinaigrette assez relevée.", "Égoutter les lentilles et mélanger au thon et aux pois chiches.", "Ajouter la vinaigrette.", "Servir froid ou tiède."]},
  {"nom": "Velouté de haricots blancs", "cat": "Légumineuses", "proteine": "végé", "source": "Marmiton", "url": "https://www.marmiton.org/recettes/recette_veloute-de-haricots-blancs_23295.aspx", "prep_min": 20, "cuisson_min": 60, "total_min": 80, "cuissons": ["casserole"], "parts_origine": 4, "saison": "Automne-hiver", "tags": ["végé"], "ingredients": [{"nom": "haricots blancs", "qte": 225, "unite": "g", "rayon": "Épicerie"}, {"nom": "lait", "qte": 1.5, "unite": "l", "rayon": "Crèmerie"}, {"nom": "beurre", "qte": 75, "unite": "g", "rayon": "Crèmerie"}, {"nom": "farine", "qte": 15, "unite": "g", "rayon": "Épicerie"}], "etapes": ["Faites tremper les haricots dans de l'eau froide pendant plusieurs heures.", "Commencez la cuisson des haricots à l'eau froide puis faites-les cuire à frémissement pendant environ 1 heure. Salez en fin de cuisson.", "Pendant ce temps, préparez la béchamel : mélangez la farine dans 30 g de beurre fondu jusqu'à ce qu'elle colore puis versez 35 cl de lait chaud en remuant sans arrêt jusqu'à ce qu'elle soit épaissie.", "Égouttez les haricots cuits et passez-les au tamis. Mélangez la purée de haricots à la béchamel, salez, poivrez puis versez le reste de lait chaud en remuant sans arrêt.", "Remettez sur le feu et laissez épaissir un peu selon la consistance voulue.", "Juste avant le service, ajoutez le reste du beurre en noix, remuez et rectifiez l'assaisonnement.", "Servez bien chaud."]},
  {"nom": "Bavette à l'échalote", "cat": "Rapide (sport)", "proteine": "bœuf", "source": "Marmiton", "url": "https://www.marmiton.org/recettes/recette_bavette-a-l-echalote_29161.aspx", "prep_min": 10, "cuisson_min": 15, "total_min": 25, "cuissons": ["poêle"], "parts_origine": 4, "saison": "Toute l'année", "tags": [], "ingredients": [{"nom": "bavettes", "qte": 4, "unite": "pièces", "rayon": "Boucherie"}, {"nom": "échalotes", "qte": 8, "unite": "pièces", "rayon": "Fruits & légumes"}, {"nom": "margarine", "qte": 1, "unite": "cuillère à soupe", "rayon": "Crèmerie"}, {"nom": "fond de sauce", "qte": 1, "unite": "cuillère à soupe", "rayon": "Épicerie"}, {"nom": "sel", "qte": 1, "unite": "pincée", "rayon": "Épicerie"}, {"nom": "poivre", "qte": 1, "unite": "pincée", "rayon": "Épicerie"}], "etapes": ["Éplucher les échalotes et les couper en rondelles.", "Les faire cuire dans une poêle avec de la margarine, saler et poivrer, ajouter le fond de sauce délayé dans de l'eau ; réserver au chaud.", "Faire cuire les bavettes selon le goût des personnes, saler et poivrer.", "Au moment de servir, recouvrir chaque bavette d'échalotes cuites et arroser avec le jus de cuisson.", "Servir avec des pommes de terre rissolées."]},
  {"nom": "Wok de bœuf aux poivrons et oignons", "cat": "Rapide (sport)", "proteine": "bœuf", "source": "Marmiton", "url": "https://www.marmiton.org/recettes/recette_wok-de-boeuf-aux-poivrons-et-oignons_33810.aspx", "prep_min": 30, "cuisson_min": 20, "total_min": 50, "cuissons": ["wok", "poêle"], "parts_origine": 2, "saison": "Toute l'année", "tags": [], "ingredients": [{"nom": "steaks", "qte": 2, "unite": "unités", "rayon": "Boucherie"}, {"nom": "poivron", "qte": 1, "unite": "unité", "rayon": "Fruits & légumes"}, {"nom": "oignons", "qte": 2, "unite": "unités", "rayon": "Fruits & légumes"}, {"nom": "sauce soja", "qte": 3, "unite": "cuillères à soupe", "rayon": "Épicerie"}, {"nom": "vinaigre balsamique", "qte": 3, "unite": "cuillères à soupe", "rayon": "Épicerie"}, {"nom": "bouillon", "qte": 0.5, "unite": "cube", "rayon": "Épicerie"}, {"nom": "noix de cajou", "qte": 1, "unite": "poignée", "rayon": "Épicerie"}, {"nom": "sel", "qte": 1, "unite": "pincée", "rayon": "Épicerie"}, {"nom": "poivre", "qte": 1, "unite": "pincée", "rayon": "Épicerie"}], "etapes": ["Couper les steaks en petits morceaux (environ 2 cm x 2 cm). Les mettre dans un plat avec 3 cuillères à soupe de vinaigre balsamique et 3 cuillères à soupe de sauce soja. Laisser reposer au frigo au moins 3 heures.", "Faire chauffer le wok (ou une poêle) avec un peu d'huile. Y faire revenir les morceaux de bœuf, sans le jus, avec un peu de sel et de poivre.", "Réserver le bœuf, et faire revenir le poivron et les oignons coupés en morceaux.", "Quand ils sont cuits, rajouter le bœuf et le jus qui restait.", "Pour avoir plus de sauce, on peut rajouter un demi-bouillon cube et un peu d'eau.", "Enfin, juste avant de servir, ajouter les noix de cajou ou amandes."]},
  {"nom": "Brochettes d'agneau à la menthe", "cat": "Rapide (sport)", "proteine": "agneau", "source": "Marmiton", "url": "https://www.marmiton.org/recettes/recette_brochettes-d-agneau-a-la-menthe_22097.aspx", "prep_min": 10, "cuisson_min": 10, "total_min": 20, "cuissons": ["grill", "four"], "parts_origine": 4, "saison": "Printemps-été", "tags": [], "ingredients": [{"nom": "noisettes d'agneau", "qte": 12, "unite": "pièces", "rayon": "Boucherie"}, {"nom": "menthe fraîche", "qte": 1, "unite": "branche", "rayon": "Fruits & légumes"}, {"nom": "citron", "qte": 0.5, "unite": "pièce", "rayon": "Fruits & légumes"}, {"nom": "huile d'olive", "qte": 3, "unite": "cuillères à soupe", "rayon": "Épicerie"}, {"nom": "sel", "qte": 1, "unite": "pincée", "rayon": "Épicerie"}, {"nom": "poivre", "qte": 1, "unite": "pincée", "rayon": "Épicerie"}], "etapes": ["Pressez le citron, mélangez le jus avec l'huile d'olive et la menthe hachée. Laissez mariner la viande dans ce mélange environ 2 h au réfrigérateur, retournez les morceaux de temps en temps.", "Préchauffer le four à 160°C (thermostat 5-6).", "Piquez les morceaux sur des brochettes et faites-les cuire au barbecue ou au four environ 10 min.", "Salez et poivrez en fin de cuisson et servez accompagné de semoule de couscous ou de riz au curry."]},
  {"nom": "Escalopes de dinde aux courgettes et au citron", "cat": "Rapide (sport)", "proteine": "volaille", "source": "Marmiton", "url": "https://www.marmiton.org/recettes/recette_escalopes-de-dinde-aux-courgettes-et-au-citron_15770.aspx", "prep_min": 15, "cuisson_min": 20, "total_min": 35, "cuissons": ["poêle"], "parts_origine": 4, "saison": "Printemps-été", "tags": [], "ingredients": [{"nom": "escalopes de dinde", "qte": 4, "unite": "pièces", "rayon": "Boucherie"}, {"nom": "courgettes", "qte": 4, "unite": "unités", "rayon": "Fruits & légumes"}, {"nom": "citron", "qte": 1, "unite": "pièce", "rayon": "Fruits & légumes"}, {"nom": "olives noires", "qte": 1, "unite": "poignée", "rayon": "Épicerie"}, {"nom": "sauge", "qte": 1, "unite": "cuillère à café", "rayon": "Épicerie"}, {"nom": "huile d'olive", "qte": 1, "unite": "cuillère à soupe", "rayon": "Épicerie"}], "etapes": ["Faire chauffer l'huile d'olive dans une poêle. Y faire revenir les escalopes coupées en morceaux.", "Ajouter les courgettes et le citron coupés en rondelles très fines. Saler, poivrer et ajouter la sauge.", "Quelques minutes avant la fin de la cuisson, ajouter quelques olives noires."]},
  {"nom": "Pavé de saumon à la poêle", "cat": "Rapide (sport)", "proteine": "poisson", "source": "Marmiton", "url": "https://www.marmiton.org/recettes/recette_recette-pave-de-saumon-a-la-poele_539428.aspx", "prep_min": 5, "cuisson_min": 10, "total_min": 15, "cuissons": ["poêle"], "parts_origine": 4, "saison": "Toute l'année", "tags": ["poisson gras"], "ingredients": [{"nom": "pavés de saumon", "qte": 4, "unite": "pièces", "rayon": "Poissonnerie"}, {"nom": "citrons", "qte": 2, "unite": "pièces", "rayon": "Fruits & légumes"}, {"nom": "aneth", "qte": 1, "unite": "bouquet", "rayon": "Fruits & légumes"}, {"nom": "huile de sésame", "qte": 2, "unite": "cuillères à soupe", "rayon": "Épicerie"}, {"nom": "sel", "qte": 2, "unite": "pincées", "rayon": "Épicerie"}, {"nom": "poivre", "qte": 2, "unite": "pincées", "rayon": "Épicerie"}], "etapes": ["Passez les pavés de saumon sous l'eau, retirez soigneusement les arêtes, puis saupoudrez légèrement la chair de sel.", "Versez un peu d'huile dans une poêle et mettez-la à chauffer. Installez les pavés côté peau contre la surface chaude.", "Laissez-les griller vivement pendant 3 minutes, puis couvrez la poêle et diminuez le feu afin de poursuivre la cuisson environ 6 minutes.", "Retournez les pavés pour faire dorer brièvement la chair, une trentaine de secondes suffit. Rehaussez de poivre, ajoutez un filet de citron et disposez une petite branche d'aneth en finition."]},
  {"nom": "Omelette blanche aux herbes", "cat": "Rapide (sport)", "proteine": "végé", "source": "Marmiton", "url": "https://www.marmiton.org/recettes/recette_omelette-blanche-aux-herbes_538422.aspx", "prep_min": 10, "cuisson_min": 6, "total_min": 16, "cuissons": ["poêle"], "parts_origine": 4, "saison": "Toute l'année", "tags": ["végé"], "ingredients": [{"nom": "blancs d'œuf", "qte": 8, "unite": "pièces", "rayon": "Crèmerie"}, {"nom": "persil", "qte": 1, "unite": "petit bouquet", "rayon": "Fruits & légumes"}, {"nom": "coriandre", "qte": 1, "unite": "petit bouquet", "rayon": "Fruits & légumes"}, {"nom": "ciboulette", "qte": 1, "unite": "petit bouquet", "rayon": "Fruits & légumes"}, {"nom": "huile d'olive", "qte": 1, "unite": "cuillère à soupe", "rayon": "Épicerie"}, {"nom": "sel", "qte": 1, "unite": "pincée", "rayon": "Épicerie"}, {"nom": "poivre du moulin", "qte": 1, "unite": "pincée", "rayon": "Épicerie"}], "etapes": ["Lavez et séchez bien les herbes aromatiques. Ciselez-les finement. Versez les blancs d'œufs dans un saladier et commencez à les battre pour les aérer.", "Quand les blancs commencent à devenir mousseux, ajoutez-leur les herbes aromatiques ciselées. Salez légèrement et poivrez plus généreusement.", "Faites chauffer une poêle et versez-y l'huile d'olive. Quand celle-ci est bien chaude, versez l'appareil à omelette en une fois et laissez saisir. Baissez le feu lorsque les bords se décollent.", "Pliez l'omelette en deux. Laissez cuire sur feu doux à moyen, puis retournez. Quand les blancs sont cuits, débarrassez et servez chaud."]},
  {"nom": "Bœuf bourguignon", "cat": "Mijoté", "proteine": "bœuf", "source": "Journal des Femmes", "url": "https://cuisine.journaldesfemmes.fr/recette/346736-boeuf-bourguignon", "prep_min": 20, "cuisson_min": 210, "total_min": 230, "cuissons": ["cocotte"], "parts_origine": 5, "saison": "Automne-hiver", "tags": ["sans champignons"], "ingredients": [{"nom": "bœuf pour bourguignon", "qte": 1500, "unite": "g", "rayon": "Boucherie"}, {"nom": "lardons", "qte": 200, "unite": "g", "rayon": "Boucherie"}, {"nom": "beurre", "qte": 60, "unite": "g", "rayon": "Crèmerie"}, {"nom": "petits oignons", "qte": 10, "unite": "unités", "rayon": "Fruits & légumes"}, {"nom": "carotte", "qte": 2, "unite": "unités", "rayon": "Fruits & légumes"}, {"nom": "ail", "qte": 2, "unite": "gousses", "rayon": "Fruits & légumes"}, {"nom": "farine", "qte": 60, "unite": "g", "rayon": "Épicerie"}, {"nom": "vin rouge Bourgogne", "qte": 50, "unite": "cl", "rayon": "Épicerie"}, {"nom": "bouillon de viande", "qte": 2, "unite": "verres", "rayon": "Épicerie"}, {"nom": "bouquet garni", "qte": 1, "unite": "unité", "rayon": "Fruits & légumes"}, {"nom": "sel", "qte": 0, "unite": "", "rayon": "Épicerie"}, {"nom": "poivre", "qte": 0, "unite": "", "rayon": "Épicerie"}], "etapes": ["Tailler le bœuf en cubes de 3 à 4 cm de côté. Peler les oignons sans les écorcher. Peler et couper les carottes en rondelles pas trop fines (2mm au minimum). Peler l'ail et enlever le germe.", "Dans une grande cocotte, faire fondre le beurre. Ajouter les oignons entiers et les lardons. Faire revenir en remuant constamment. Lorsqu'ils sont dorés, les retirer avec un écumoire, et réserver.", "Dans la même cocotte, faire revenir les morceaux de viande à feu vif. Ajouter les carottes, et faire revenir encore 5 mn.", "Lorsque la viande est bien dorée, saupoudrer de farine (60g) et laisser roussir en remuant toujours.", "Verser le bouillon préparé (2 cubes dans 50 cl d'eau bouillante). Bien gratter les sucs. Remettre les lardons et les oignons dans la cocotte. Verser le vin rouge. Saler, poivrer et ajouter le bouquet garni et les gousses d'ail écrasées. Porter à ébullition. Couvrir et laisser mijoter doucement pendant 3 heures.", "Retirer le bouquet garni et verser dans un plat. Servir avec des pâtes ou des pommes de terre vapeur."]},
  {"nom": "Pot-au-feu", "cat": "Mijoté", "proteine": "bœuf", "source": "Marmiton", "url": "https://www.marmiton.org/recettes/recette_pot-au-feu-facile_44578.aspx", "prep_min": 30, "cuisson_min": 120, "total_min": 150, "cuissons": ["cocotte"], "parts_origine": 4, "saison": "Hiver", "tags": [], "ingredients": [{"nom": "sel", "qte": 1, "unite": "cuillère à café", "rayon": "Épicerie"}, {"nom": "poivre", "qte": 1, "unite": "cuillère à café", "rayon": "Épicerie"}, {"nom": "poireaux", "qte": 2, "unite": "unités", "rayon": "Fruits & légumes"}, {"nom": "oignon", "qte": 1, "unite": "unité", "rayon": "Fruits & légumes"}, {"nom": "clous de girofle", "qte": 4, "unite": "unités", "rayon": "Épicerie"}, {"nom": "carottes", "qte": 5, "unite": "unités", "rayon": "Fruits & légumes"}, {"nom": "bœuf à pot-au-feu", "qte": 1, "unite": "kg", "rayon": "Boucherie"}, {"nom": "os à moelle", "qte": 1, "unite": "par personne", "rayon": "Boucherie"}, {"nom": "chou-rave ou navets", "qte": 4, "unite": "unités", "rayon": "Fruits & légumes"}, {"nom": "céleri", "qte": 2, "unite": "branches", "rayon": "Fruits & légumes"}, {"nom": "ail", "qte": 1, "unite": "gousse", "rayon": "Fruits & légumes"}, {"nom": "bouquet garni (thym, laurier, persil)", "qte": 1, "unite": "unités", "rayon": "Fruits & légumes"}], "etapes": ["Laver, éplucher tous les légumes, et les couper en morceaux assez gros.", "Piquer l'oignon entier avec les clous de girofle.", "Faire bouillir 3 litres d'eau, ajouter tous les légumes, puis le bouquet garni, l'ail, sel, poivre puis la viande.", "Faire cuire le tout pendant environ 2 h 30-3 h, écumer de temps en temps.", "1 h avant la fin, ajouter les os à moelle, et mettre du gros sel aux extrémités pour conserver la moelle.", "Egoutter les légumes et la viande, et servir bien chaud avec de la moutarde."]},
  {"nom": "Blanquette de veau", "cat": "Mijoté", "proteine": "veau", "source": "Journal des Femmes", "url": "https://cuisine.journaldesfemmes.fr/recette/330052-blanquette-de-veau", "prep_min": 45, "cuisson_min": 90, "total_min": 135, "cuissons": ["cocotte"], "parts_origine": 4, "saison": "Automne-hiver", "tags": ["sans champignons"], "ingredients": [{"nom": "épaule de veau en morceaux", "qte": 1, "unite": "kg", "rayon": "Boucherie"}, {"nom": "oignon", "qte": 2, "unite": "unités", "rayon": "Fruits & légumes"}, {"nom": "carotte", "qte": 2, "unite": "unités", "rayon": "Fruits & légumes"}, {"nom": "céleri", "qte": 1, "unite": "branche", "rayon": "Fruits & légumes"}, {"nom": "poireau", "qte": 1, "unite": "unité", "rayon": "Fruits & légumes"}, {"nom": "thym", "qte": 0, "unite": "", "rayon": "Fruits & légumes"}, {"nom": "laurier", "qte": 0, "unite": "", "rayon": "Fruits & légumes"}, {"nom": "clous de girofle", "qte": 3, "unite": "unités", "rayon": "Épicerie"}, {"nom": "beurre", "qte": 85, "unite": "g", "rayon": "Crèmerie"}, {"nom": "farine", "qte": 70, "unite": "g", "rayon": "Épicerie"}, {"nom": "crème fraîche", "qte": 20, "unite": "cl", "rayon": "Crèmerie"}, {"nom": "sel", "qte": 0, "unite": "", "rayon": "Épicerie"}, {"nom": "poivre", "qte": 0, "unite": "", "rayon": "Épicerie"}], "etapes": ["Mettre la viande et les légumes dans un grand faitout. Couvrir les morceaux de veau avec de l'eau froide, ajouter les 2 oignons, les carottes, la branche de céleri, le poireau, le thym, le laurier, les clous de girofle, saler.", "Porter à ébullition, puis laisser frémir pendant une heure, écumer de temps en temps. La viande étant cuite, la retirer et la maintenir au chaud. Passer le bouillon.", "Préparer un roux blanc avec 70 g de beurre et autant de farine, mouiller avec 1 litre de bouillon très chaud, porter à ébullition en remuant sans cesse, ajouter la crème fraîche, laisser réduire, poivrer.", "Baisser le feu. Remettre les morceaux de viande dans la sauce. Vérifier l'assaisonnement et laisser frémir tout doucement encore quelques minutes."]},
  {"nom": "Jarret de veau braisé au vin blanc", "cat": "Mijoté", "proteine": "veau", "source": "Marmiton", "url": "https://www.marmiton.org/recettes/recette_osso-bucco-de-veau-sans-tomates_221495.aspx", "prep_min": 20, "cuisson_min": 120, "total_min": 140, "cuissons": ["cocotte"], "parts_origine": 4, "saison": "Automne-hiver", "tags": [], "ingredients": [{"nom": "huile d'olive", "qte": 2, "unite": "cuillères à soupe", "rayon": "Épicerie"}, {"nom": "sel", "qte": 0, "unite": "", "rayon": "Épicerie"}, {"nom": "poivre", "qte": 0, "unite": "", "rayon": "Épicerie"}, {"nom": "oignons", "qte": 2, "unite": "unités", "rayon": "Fruits & légumes"}, {"nom": "carottes", "qte": 6, "unite": "unités", "rayon": "Fruits & légumes"}, {"nom": "farine", "qte": 1, "unite": "tasse", "rayon": "Épicerie"}, {"nom": "jarrets de veau", "qte": 4, "unite": "tranches", "rayon": "Boucherie"}, {"nom": "ail", "qte": 3, "unite": "gousses", "rayon": "Fruits & légumes"}, {"nom": "vin blanc", "qte": 50, "unite": "cl", "rayon": "Épicerie"}, {"nom": "bouquet garni", "qte": 1, "unite": "unité", "rayon": "Fruits & légumes"}], "etapes": ["Couper en rondelles les oignons et les carottes, fariner les tranches de jarret (enlever le surplus de farine).", "Faire revenir dans une cocotte les oignons et les carottes avec de l'huile d'olive et les réserver quand ils sont saisis.", "Faire revenir les tranches de jarret farinées et réserver.", "Réduire le feu et déglacer la cocotte avec le vin blanc.", "Ajouter les jarrets, les oignons, les carottes, l'ail coupé en deux et le bouquet garni. Mettre de l'eau, saler et poivrer, fermer la cocotte.", "Laisser cuire 1h30 à 2h selon l'épaisseur des morceaux, jusqu'à ce que la viande se détache de l'os."]},
  {"nom": "Joues de porc au cidre", "cat": "Mijoté", "proteine": "porc", "source": "Marmiton", "url": "https://www.marmiton.org/recettes/recette_joues-de-porc-confites-au-cidre_40485.aspx", "prep_min": 30, "cuisson_min": 120, "total_min": 150, "cuissons": ["cocotte"], "parts_origine": 8, "saison": "Automne-hiver", "tags": [], "ingredients": [{"nom": "sel", "qte": 1, "unite": "pincée", "rayon": "Épicerie"}, {"nom": "poivre", "qte": 1, "unite": "pincée", "rayon": "Épicerie"}, {"nom": "beurre", "qte": 1, "unite": "cuillère à soupe", "rayon": "Crèmerie"}, {"nom": "oignon", "qte": 1, "unite": "unité", "rayon": "Fruits & légumes"}, {"nom": "huile", "qte": 1, "unite": "cuillère à soupe", "rayon": "Épicerie"}, {"nom": "joue de porc", "qte": 8, "unite": "pièces", "rayon": "Boucherie"}, {"nom": "lard de poitrine frais", "qte": 400, "unite": "g", "rayon": "Boucherie"}, {"nom": "pomme de terre", "qte": 1, "unite": "kg", "rayon": "Fruits & légumes"}, {"nom": "cidre bouché brut", "qte": 50, "unite": "cl", "rayon": "Épicerie"}, {"nom": "herbes de Provence", "qte": 1, "unite": "cuillère à café", "rayon": "Épicerie"}], "etapes": ["Faire revenir environ 10 minutes les joues de porc dans un mélange huile + beurre, puis les mettre de côté.", "Peler les pommes de terre et les couper en quartiers. Les sécher pour enlever l'excès d'amidon.", "Peler et couper l'oignon en morceaux relativement gros. Désosser le lard (conserver la couenne) et le couper en gros lardons.", "Faire revenir à feu vif le lard et les oignons dans un mélange huile + beurre, ajouter ensuite les pommes de terre et laisser revenir environ 10 minutes.", "Ajouter les joues de porc réservées. Assaisonner (sel, poivre, herbes de Provence). Arroser avec le cidre.", "Réduire le feu et laisser mijoter 1h30 à couvert en écumant de temps à autre.", "Oter le couvercle et continuer à cuire au moins 30 minutes, jusqu'à ce que la sauce enrobe les pommes de terre.", "Servir chaud avec une salade verte."]},
  {"nom": "Chou farci", "cat": "Mijoté", "proteine": "porc", "source": "Marmiton", "url": "https://www.marmiton.org/recettes/recette_choux-farcis_21814.aspx", "prep_min": 40, "cuisson_min": 90, "total_min": 130, "cuissons": ["cocotte"], "parts_origine": 4, "saison": "Automne-hiver", "tags": [], "ingredients": [{"nom": "sel", "qte": 1, "unite": "pincée", "rayon": "Épicerie"}, {"nom": "oignons", "qte": 3, "unite": "unités", "rayon": "Fruits & légumes"}, {"nom": "carottes", "qte": 3, "unite": "unités", "rayon": "Fruits & légumes"}, {"nom": "chou", "qte": 1, "unite": "moyen", "rayon": "Fruits & légumes"}, {"nom": "margarine", "qte": 6, "unite": "cuillères à café", "rayon": "Crèmerie"}, {"nom": "poivre", "qte": 1, "unite": "pincée", "rayon": "Épicerie"}, {"nom": "persil", "qte": 1, "unite": "botte", "rayon": "Fruits & légumes"}, {"nom": "bœuf haché", "qte": 200, "unite": "g", "rayon": "Boucherie"}, {"nom": "haché de veau", "qte": 200, "unite": "g", "rayon": "Boucherie"}, {"nom": "biscottes", "qte": 3, "unite": "unités", "rayon": "Boulangerie"}, {"nom": "ail", "qte": 1, "unite": "gousse", "rayon": "Fruits & légumes"}], "etapes": ["Séparer les feuilles de chou.", "Faire blanchir les feuilles 10 min dans l'eau bouillante.", "Préparer la farce: mélanger les viandes dans un saladier. Saler et poivrer. Ajouter les biscottes émiettées, le persil ciselé et l'ail haché. Bien mélanger.", "Egoutter les feuilles du chou.", "Etaler par 2 ou 3 feuilles. Disposer dessus un quart de la farce.", "Rouler avec soin en enfermant bien la farce. Ficeler.", "Faire dorer ces paquets dans la cocotte avec la margarine.", "Peler les carottes et les oignons, les ajouter et mouiller avec de l'eau ou du vin blanc.", "Cuire à feu doux pendant 1h15."]},
  {"nom": "Tajine d'agneau citron confit et olives", "cat": "Mijoté", "proteine": "agneau", "source": "Marmiton", "url": "https://www.marmiton.org/recettes/recette_tajine-d-agneau-aux-citrons-confits-et-olives_26363.aspx", "prep_min": 30, "cuisson_min": 120, "total_min": 150, "cuissons": ["cocotte", "four"], "parts_origine": 6, "saison": "Toute l'année", "tags": [], "ingredients": [{"nom": "huile d'olive", "qte": 1, "unite": "cuillère à soupe", "rayon": "Épicerie"}, {"nom": "sel", "qte": 1, "unite": "pincée", "rayon": "Épicerie"}, {"nom": "poivre", "qte": 1, "unite": "pincée", "rayon": "Épicerie"}, {"nom": "gingembre frais", "qte": 1, "unite": "morceau", "rayon": "Fruits & légumes"}, {"nom": "citrons confits", "qte": 4, "unite": "unités", "rayon": "Épicerie"}, {"nom": "oignon", "qte": 1, "unite": "unités", "rayon": "Fruits & légumes"}, {"nom": "coriandre fraîche", "qte": 1, "unite": "cuillère à soupe", "rayon": "Fruits & légumes"}, {"nom": "cumin", "qte": 1, "unite": "cuillère à soupe", "rayon": "Épicerie"}, {"nom": "piment doux rouge en poudre", "qte": 1, "unite": "cuillère à café", "rayon": "Épicerie"}, {"nom": "épaule d'agneau coupée en morceaux", "qte": 1.5, "unite": "kg", "rayon": "Boucherie"}, {"nom": "olives noires", "qte": 200, "unite": "g", "rayon": "Épicerie"}, {"nom": "ail", "qte": 2, "unite": "gousses", "rayon": "Fruits & légumes"}, {"nom": "eau chaude", "qte": 50, "unite": "cl", "rayon": "Épicerie"}], "etapes": ["Dans une cocotte, chauffer l'huile d'olive, y faire revenir l'oignon haché et l'ail écrasé. Ajouter les morceaux d'agneau et les laisser dorer. Râper le gingembre frais et mélanger avec le cumin et le piment doux à la viande.", "Mouiller avec l'eau chaude pour déglacer le plat. Transvaser dans un plat à tajine, ajouter les citrons coupés en deux et la coriandre. Assaisonner (peu de sel à cause des olives). Couvrir et mettre au four à 180°C pendant 1h30.", "Sortir le plat du four, déposer les olives sur la viande.", "Couvrir à nouveau et remettre au four 1h."]},
  {"nom": "Coq au vin", "cat": "Mijoté", "proteine": "volaille", "source": "Journal des Femmes", "url": "https://cuisine.journaldesfemmes.fr/recette/326735-coq-au-vin", "prep_min": 30, "cuisson_min": 210, "total_min": 240, "cuissons": ["cocotte"], "parts_origine": 6, "saison": "Automne-hiver", "tags": ["sans champignons"], "ingredients": [{"nom": "coq", "qte": 3.5, "unite": "kg", "rayon": "Boucherie"}, {"nom": "vin rouge corsé type Bourgogne", "qte": 0.5, "unite": "bouteille", "rayon": "Épicerie"}, {"nom": "lard en cube", "qte": 150, "unite": "g", "rayon": "Boucherie"}, {"nom": "oignon blanc", "qte": 24, "unite": "unités", "rayon": "Fruits & légumes"}, {"nom": "ail", "qte": 3, "unite": "gousses", "rayon": "Fruits & légumes"}, {"nom": "carotte", "qte": 4, "unite": "unités", "rayon": "Fruits & légumes"}, {"nom": "huile de tournesol", "qte": 1, "unite": "filet", "rayon": "Épicerie"}, {"nom": "beurre doux", "qte": 1, "unite": "noix", "rayon": "Crèmerie"}, {"nom": "thym", "qte": 2, "unite": "brins", "rayon": "Fruits & légumes"}, {"nom": "laurier", "qte": 1, "unite": "feuille", "rayon": "Fruits & légumes"}, {"nom": "persil", "qte": 1, "unite": "peu", "rayon": "Fruits & légumes"}, {"nom": "sel de mer", "qte": 1, "unite": "pincée", "rayon": "Épicerie"}, {"nom": "poivre noir du moulin", "qte": 1, "unite": "pincée", "rayon": "Épicerie"}, {"nom": "pomme de terre Roseval", "qte": 2, "unite": "kg", "rayon": "Fruits & légumes"}], "etapes": ["La veille, nettoyer et couper le coq en morceaux. Verser 1/2 bouteille de Bourgogne rouge sur le coq. Ajouter les petits oignons blancs, les carottes pelées et coupées en quartiers et les herbes. Couvrir et mettre au réfrigérateur 1 jour.", "Le jour suivant, retirer et égoutter le coq et les légumes. Garder le vin. Faire brunir le coq dans l'huile. Ajouter l'ail aux légumes et chauffer quelques minutes.", "Mettre le coq et les légumes dans une cocotte en fonte. Verser le vin de la marinade. Saler, poivrer. Amener à ébullition à feu moyen. Couvrir, réduire le feu au minimum. Laisser cuire 3h30.", "Préparer les pommes de terre vapeur en accompagnement.", "Faire brunir le lard et les oignons blancs pendant 10 minutes environ. Quand le coq est prêt, ajouter le lard et les oignons dans la cocotte et remuer 2 à 3 minutes. Rectifier l'assaisonnement, ajouter du persil."]},
];

/* Contrainte par jour de la semaine */
window.CADRE = [
  {
    "jour": "Lun",
    "cats": [
      "Volaille"
    ],
    "maxMin": 35,
    "note": "Volaille, rapide"
  },
  {
    "jour": "Mar",
    "cats": [
      "Légumineuses"
    ],
    "maxMin": null,
    "note": "Légumineuses / semi-végé"
  },
  {
    "jour": "Mer",
    "cats": [
      "Porc"
    ],
    "maxMin": 35,
    "note": "Porc, rapide"
  },
  {
    "jour": "Jeu",
    "cats": [
      "Poisson"
    ],
    "maxMin": null,
    "note": "Poisson"
  },
  {
    "jour": "Ven",
    "cats": [
      "Rapide (sport)"
    ],
    "maxMin": 25,
    "note": "Express, riche en protéines (retour du sport)"
  },
  {
    "jour": "Sam",
    "cats": [
      "Mijoté"
    ],
    "maxMin": null,
    "note": "Mijoté, on a le temps"
  },
  {
    "jour": "Dim",
    "cats": [
      "Mijoté",
      "Rôti"
    ],
    "maxMin": null,
    "note": "Mijoté ou rôti du dimanche"
  }
];

/* Ingrédients exclus par défaut (l'utilisateur peut en ajouter dans Réglages) */
window.EXCLUS_DEFAUT = ["abats", "tomate", "champignon", "sucré-salé"];

/* Saveurs dominantes — évite deux plats de même saveur dans la semaine */
window.SAVEURS = ["moutarde", "cidre", "curry", "coco", "vin rouge", "vin blanc", "citron confit", "soja"];
